PERMISSION_CREATE = "permission:create"
PERMISSION_VIEW = "permission:view"
PERMISSION_UPDATE = "permission:update"
PERMISSION_DELETE = "permission:delete"

ROLE_CREATE = "role:create"
ROLE_VIEW = "role:view"
ROLE_UPDATE = "role:update"
ROLE_DELETE = "role:delete"
ASSIGN_PERMISSION = "assign_permission:create"
UNASSIGN_PERMISSION = "unassign_permission:delete"
USER_PERMISSION = "user_permission:view"

ASSIGN_ROLE = "assign_role:create"
UNASSIGN_ROLE = "unassign_role:delete"

USER_VIEW = "user:view"
USER_CREATE = "user:create"
USER_UPDATE = "user:update"
USER_DELETE = "user:delete"
